ip-reputation:
    build: ./ip-reputation
    environment:
      - QUEUE_URL=redis://queue:6379/0
      - BLACKLIST_FILE=/app/blacklist.txt
      - CHECK_INTERVAL=60
      - BLACKLISTS=zen.spamhaus.org,dnsbl.sorbs.net
      - SMTP_SERVER=smtp1
      - SMTP_PORT=25
      - EMAIL_FROM=alert@yourdomain.com
      - ADMIN_EMAIL=admin@yourdomain.com
      - CACHE_TTL=3600
      - ALERT_COOLDOWN=3600
      - LOG_LEVEL=INFO
    volumes:
      - ./ip-reputation/blacklist.txt:/app/blacklist.txt
      - ./ip-reputation/logs:/app/logs
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://queue:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3